name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        # Quitamos la línea de cache: gradle aquí para evitar el error 400 de GitHub

    - name: Inyectar API Key de Gemini
      run: echo "gemini.api.key=${{ secrets.GEMINI_API_KEY }}" >> local.properties

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        cache-disabled: true # Apagamos el caché problemático por completo

    - name: Compilar el APK
      # El --no-daemon evita que el KSP se crashee en la nube
      run: gradle assembleDebug --no-daemon 

    - name: Subir el APK para descargar
      uses: actions/upload-artifact@v4
      with:
        name: Acordify-APK
        path: '**/*.apk'
